image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: install-dependencies
    init: ""
    command: ""
ports:
  - port: 9042
    onOpen: ignore
  - port: 7000
    onOpen: ignore
  - port: 7199
    onOpen: ignore    
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
